### ISSUE TITLE
mut_type_occurrences error with low mutated samples

### ISSUE THREAD

**Issue by tangwei1129** [CuppenResearch/MutationalPatterns#7]
mut_type_occurrences(gr.list, ref_genome)
when I ran this, I got an error with "Error in ans[] <- x : replacement has length zero". I checked the samples and found one sample has only 1 mutation.
I wonder how can I modify the function to happen the function work?
Thanks

**Comment by roelj** [comment]
Thanks for reporting this issue.  Could you provide me with a complete sequence of commands that lead to this error? e.g.:
```{r}
ref_genome = "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)
gr.list <- read_vcfs_as_granges (..., ...)
...
```

That way I can try to reproduce the problem and attempt to solve it.

**Comment by tangwei1129** [comment]
library(BSgenome)
ref_genome = "BSgenome.Hsapiens.UCSC.hg19"
library(ref_genome, character.only = TRUE)



## covert to GRangesList ##
head(test)
   Source CHROM       POS REF ALT
1 PT10097  chr1  32745370   G   T
2 PT10097  chr1 201030553   G   A
3 PT10097  chr2 141128470   C   T
4 PT10097  chr2 141267616   G   T
5 PT10097  chr1 114943957   T   A
6 PT10097  chr2 190719500   G   T

gr=list()
for (i in 1:length(levels(test$Source))){
temp=subset(test,Source==levels(test$Source)[i])
gr[[i]]=GRanges(seqnames=temp$CHROM,
   ranges=IRanges(temp$POS,temp$POS),
REF=temp$REF,
ALT=temp$ALT

)


}
gr.list<- GRangesList(gr)
names(gr.list)=levels(test$Source)

library(MutationalPatterns)

type_occurrences = mut_type_occurrences(gr.list, ref_genome)
Error in ans[] <- x : replacement has length zero


2017-01-19 4:08 GMT-05:00 Roel Janssen <notifications@github.com>:

**Comment by tangwei1129** [comment]
> mut_type_occurrences(gr.list[1], ref_genome)
        C>A C>G C>T T>A T>C T>G C>T at CpG C>T other
PT10097  14  10   8   3   5   0          1         7
> mut_type_occurrences(gr.list[110], ref_genome)
Error in ans[] <- x : replacement has length zero
> gr.list[110]
GRangesList object of length 1:
$PT25133
GRanges object with 1 range and 2 metadata columns:
      seqnames               ranges strand |      REF      ALT
         <Rle>            <IRanges>  <Rle> | <factor> <factor>
  [1]    chr12 [25398285, 25398285]      * |        C        A

-------
seqinfo: 23 sequences from an unspecified genome; no seqlengths


2017-01-19 4:08 GMT-05:00 Roel Janssen <notifications@github.com>:

**Comment by tangwei1129** [comment]
I think perhaps it happens when the C>T count 0.

2017-01-19 4:08 GMT-05:00 Roel Janssen <notifications@github.com>:

**Comment by roelj** [comment]
Thanks for your code samples.  I have been able to reproduce the problem, and identify the cause in the code.  I will verify the fix with my colleague and let you know how to get the updated version once we push the fix.

**Comment by roelj** [comment]
Hi @tangwei1129. Could you verify that the problem has been resolved now?
To do so, you have to load the package from Github.  The easiest way to do that is by running:
```{r}
install.packages("devtools")
library(devtools)
install_github("CuppenResearch/MutationalPatterns")
library(MutationalPatterns)
```

Thanks!

**Comment by tangwei1129** [comment]
Hi Roel,
thank you for your prompt fix.
the error for  mut_type_occurrences function has been fixed. however, some
following function such as plot_spectrum and mut_matrix still do not work
properly.
plot_spectrum does not output graph.

> plot_spectrum(type_occurrences, CT = TRUE)
Warning messages:
1: Removed 7 rows containing missing values
(position_stack).
2: Removed 7 rows containing missing values
(geom_errorbar).


> test_matrix = mut_matrix(vcf_list = gr.list.cl,ref_genome = ref_genome)
Error in ans[] <- x : replacement has length zero


2017-01-20 5:15 GMT-05:00 Roel Janssen <notifications@github.com>:

**Comment by roelj** [comment]
Hi @tangwei1129.  That's unfortunate.  I believe it's the same kind of problem, but please allow me some time to properly test further fixes.

**Comment by roelj** [comment]
Hi @tangwei1129.  I am not able to reproduce the errors you posted.  Is there any code you're running, but haven't posted?  If so, could you post that?  Thanks!

**Comment by tangwei1129** [comment]
Hi Roel,
I attached the workspace and code I used. the data I tested allowed several
low mutated samples.You can try it, and it should produce the error I
mentioned before.
and the following are the packages I loaded.

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] MutationalPatterns_1.1.0          NMF_0.20.6
 [3] Biobase_2.34.0                    cluster_2.0.4
 [5] rngtools_1.2.4                    pkgmaker_0.22
 [7] registry_0.3                      BSgenome.Hsapiens.UCSC.hg19_1.4.0
 [9] BSgenome_1.42.0                   rtracklayer_1.34.1
[11] Biostrings_2.42.1                 XVector_0.14.0
[13] GenomicRanges_1.26.2              GenomeInfoDb_1.10.2
[15] IRanges_2.8.1                     S4Vectors_0.12.0
[17] BiocGenerics_0.20.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7                pracma_1.9.9
 [3] plyr_1.8.4                 RColorBrewer_1.1-2
 [5] GenomicFeatures_1.26.0     bitops_1.0-6
 [7] iterators_1.0.8            tools_3.3.1
 [9] zlibbioc_1.20.0            biomaRt_2.30.0
[11] digest_0.6.10              RSQLite_1.0.0
[13] tibble_1.2                 gtable_0.2.0
[15] lattice_0.20-33            gridBase_0.4-7
[17] Matrix_1.2-6               foreach_1.4.3
[19] DBI_0.5-1                  gridExtra_2.2.1
[21] stringr_1.1.0              grid_3.3.1
[23] AnnotationDbi_1.36.0       XML_3.98-1.4
[25] BiocParallel_1.8.1         reshape2_1.4.2
[27] ggplot2_2.2.1              magrittr_1.5
[29] Rsamtools_1.26.1           scales_0.4.1
[31] codetools_0.2-14           GenomicAlignments_1.10.0
[33] assertthat_0.1             SummarizedExperiment_1.4.0
[35] xtable_1.8-2               colorspace_1.2-7
[37] quadprog_1.5-5             stringi_1.1.2
[39] lazyeval_0.2.0             munsell_0.4.3
[41] RCurl_1.95-4.8             doParallel_1.0.10
[43] VariantAnnotation_1.20.2



2017-01-23 4:42 GMT-05:00 Roel Janssen <notifications@github.com>:

**Comment by roelj** [comment]
Hi @tangwei1129.  It looks like the attachment is missing.

**Comment by tangwei1129** [comment]
i see, github does not accept the files with certain format.
I add subfix '.txt' to the files. hope you can see the attachment.


[test.R.txt](https://github.com/CuppenResearch/MutationalPatterns/files/724575/test.R.txt)
[test.RData.txt](https://github.com/CuppenResearch/MutationalPatterns/files/724574/test.RData.txt)

**Comment by roelj** [comment]
Yes, thanks!  I'm looking into it.

**Comment by roelj** [comment]
Hi @tangwei1129.

Some of the `GRanges` objects have no ranges (which means there is no data inside them).
I added some checks and display `warnings` where appropriate. 

The `mut_matrix` function has been fixed now.  I don't know why there are no bars in the plot.

**Comment by tangwei1129** [comment]
thank you, I got it. some of the samples did not have any mutation at all.

may I ask you one more question, for this analysis, should I include all
the mutations (silent, intron, utr, etc), or only use non-silent ones? what
do you suggest?

2017-01-24 4:33 GMT-05:00 Roel Janssen <notifications@github.com>:

**Comment by FrancisBlokzijl** [comment]
That really depends on the question that you want to address. But in general I would say that if you are interested in which mutational processes are active in your sample, then you should consider all point mutations. You can find a lot of papers on mutational signatures, some nice reviews as well. Good luck!

Best,
Francis

**Comment by tangwei1129** [comment]
Thank you, Francis.

2017-01-24 10:52 GMT-05:00 Francis Blokzijl <notifications@github.com>:

> That really depends on the question that you want to address. But in
> general I would say that if you are interested in which mutational
> processes are active in your sample, then you should consider all point
> mutations. You can find a lot of papers on mutational signatures, some nice
> reviews as well. Good luck!
>
> Best,
> Francis
>

**Comment by roelj** [comment]
Thanks for reporting these issues.  I think we solved the problems, so I am closing this issue.

**Comment by tangwei1129** [comment]
thank you, pls do

2017-01-25 12:22 GMT-05:00 Roel Janssen <notifications@github.com>:
